version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    binary: surge
    main: .
    ldflags:
      - -s -w 
      - -X github.com/surge-downloader/surge/cmd.Version={{.Version}}
      - -X github.com/surge-downloader/surge/cmd.BuildTime={{.Date}}

changelog:
  sort: asc

  footer: |
    ---
    **Enjoying Surge?** Consider supporting the project to keep it blazing fast!
    - [Buy Me a Coffee](https://buymeacoffee.com/surge.downloader)
  filters:
    exclude:
      - "^docs:"
      - "^test:"

archives:
  - formats: [ tar.gz ]
    format_overrides:
      - goos: windows
        formats: [ zip ]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

homebrew_casks:
  - name: surge
    repository:
      owner: surge-downloader
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/surge-downloader/surge"
    
    description: "Blazing fast TUI download manager built in Go for power users"
    license: "MIT"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/surge"]
          end
